export const GET_FAVORITES_REQUEST = "FAVORITES_REQUEST";
export const GET_FAVORITES_SUCCESS = "FAVORITES_SUCCESS";
export const GET_FAVORITES_FAIL = "FAVORITES_FAIL";

export const ADD_FAVORITE_REQUEST = "ADD_FAVORITE_REQUEST";
export const ADD_FAVORITE_SUCCESS = "ADD_FAVORITE_SUCCESS";
export const ADD_FAVORITE_FAIL = "ADD_FAVORITE_FAIL";

export const REMOVE_FAVORITE_REQUEST = "REMOVE_FAVORITE_REQUEST";
export const REMOVE_FAVORITE_SUCCESS = "REMOVE_FAVORITE_SUCCESS";
export const REMOVE_FAVORITE_FAIL = "REMOVE_FAVORITE_FAIL";